wip: fix TranslatableServiceBehaviorCompontents
This fixes the following (which I got while trying to update the
migrations with makemigrations):

SystemCheckError: System check identified some issues:

ERRORS:

shoop.FixedCostBehaviorComponent.polymorphic_ctype: (models.E006) The
field 'polymorphic_ctype' clashes with the field 'polymorphic_ctype'
from model 'shoop.servicebehaviorcomponent'.

shoop.WaivingCostBehaviorComponent.polymorphic_ctype: (models.E006) The
field 'polymorphic_ctype' clashes with the field 'polymorphic_ctype'
from model 'shoop.servicebehaviorcomponent'.